CREATE TABLE TBL_AP_OBJECT_LOOKUP_PICARD
(
 DUMMY_ID SMALLINT,
 TBL_NAME CHARACTER VARYING(50),
 DISTRIBUTION_KEY CHARACTER VARYING(50),
 STATUS BOOLEAN,
 DATE_MODIFIED TIMESTAMP,
 REFRESH_PERIOD_FLAG CHARACTER(1),
 MAX_ERRORS BIGINT
);
